#!/bin/bash

# all backing up scripts combined into one
# -e enables translation of \t

# append success or failure depending on the outcome of commands to each message
# then output them all at once, instead of getting inline errors

pre_s='done \t'
pre_f='\033[1m\033[91mfail\033[0m \t'
pre=''
msg=''


# .bash_history
if cp ~/.bash_history ~/Dropbox/Manjaro/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre .bash_history\n"

# rofi cache and history
if cp ~/.cache/rofi-3.runcache ~/Dropbox/Manjaro/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre rofi cache/history\n"

# Rimworld modlists
if cp ~/.config/unity3d/Ludeon\ Studios/RimWorld\ by\ Ludeon\ Studios/ModLists/* ~/Dropbox/RimWorld/ModLists/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre rimworld modlists\n"

# ripme history and config
if cp ~/.config/ripme/* ~/Dropbox/Manjaro/ripme/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre ripme config/history\n"

# Rimworld mod configs
if cp ~/.config/unity3d/Ludeon\ Studios/RimWorld\ by\ Ludeon\ Studios/Config/* ~/Dropbox/RimWorld/Config/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre rimworld configs\n"

# SG logs
if cp /mnt/disk-f/_suicidegirls/__n/log ~/Dropbox/sg/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre sg log\n"

# SG archive logs
if cp /mnt/disk-f/_suicidegirls/__n/log_arch ~/Dropbox/sg/; then
	pre=$pre_s
else
	pre=$pre_f
fi
msg+="$pre sg arch log"


echo -e "$msg"
