#!/bin/bash

# grep from myLogs.txt

path=~/Dropbox/Other/myLogs.txt
help_d=$'Usage: catl -d 1..31\nfor "-d" search: catl -d 0'
help_l=$'Usage: catl -l 1..n\nfor "-l" search: catl -l 0'
help_h=$'Usage: catl [OPTIONS]

Options:
  -d INT[1..31]\tGrep entries with given day of the month.
	\t-d 0 to grep "-d"
  -l INT[1..n]\tGrep the last N entries.
	\t-l 0 to grep "-l"
  -h, --help\tShow this message and exit.
	\t-h/--help 0 to grep "-h" or "--help"'


while [ $# -gt 0 ]
do
	case $1 in
		# TODO: catch non-int values for length and day, probably also print out the help
		-l) length="$2"; shift 2 ;;
		-d) day="$2"; shift 2 ;;
		*) arg="$1"; shift 1 ;;
	esac
done

# if no arg && no length && no day
# set today as arg
if [[ -z "${arg+x}" && -z "${length+x}" && -z "${day+x}" ]]; then
	arg=`date +%Y.%m.%d`
fi

# set arg as date of the given day
# append a leading 0 if only 1 digit is entered
if [ -n "${day+x}" ]; then
	if [[ ${#day} == 1 ]]; then
			day="0$day"
	fi
	arg=`date +%Y.%m.`$day
fi

# if lenght is provided tail accordingly
# -l %d -d %d
# -l %d %arg
# ---
# -l %d
# else just pipe arg into less without tail
# -d %d
# %arg
if [ -n "${length+x}" ]; then
	if [ -n "${arg+x}" ]; then
		cat $path | grep -i --color=always -e "$arg" | tail -$length | less -R
	else
		cat $path | tail -$length | less
	fi
else
	cat $path | grep -i --color=always -e "$arg" | less -R
fi
