#!/bin/bash

# will be ex with a filename to output dir functionality

file=$1
dir="${file%.*}"

if [ -f "$file" ]; then
	case $file in
		*.7z)  7z x "$file" -o"$dir"   ;;
		*.rar) unrar x "$file" "$dir"  ;;
		*.zip) unzip "$file" -d "$dir" ;;
		*)     echo "'$file' could not be extracted with exo." ;;
	esac
else
	echo "'$file' is not a valid file."
fi
