#!/bin/bash

# move files in ~/Downloads into separate directories based on file extensions
# direct port of batch version below
# https://github.com/kittenparry/small-scripts/blob/master/bat/move.bat

dwn=~/Downloads
folders=(f.torrent f.img f.webm f.exe f.comp f.vid f.oth)

# extension arrays
ex_tor=(torrent)
ex_img=(jpg png gif jpeg bmp webp
	JPG PNG)
ex_web=(webm)
ex_exe=(exe msi) # probably unnecessary
ex_com=(rar zip 7z dmg tar.xz)
ex_vid=(mp4 avi flv ts mov wmv mkv 3gp m4v mpg
	MOV MP4)
ex_oth=(
	pdf mp3 txt iso docx rtf svg js pptx doc
	m4a html css ogg xlsx gz azw3 mobi log jar
	scs swf ods db xml ini sh php ogx save
	htmlz h class rpa rpy sav package ttf bk2 csv
	renpy srt apk sdltm dll py pak vsix icns circ
	pls bat c
)

# create subfolders if they don't exist
for f in "${folders[@]}"
do
	if [ ! -d $dwn/$f ]; then
		mkdir $dwn/$f
		echo -e "$dwn/$f\tcreated"
	# else
	# 	echo -e "$dwn/$f\talready exists"
	fi
done

cd ~/Downloads

# -v verbose, makes it so you can see the file is moved (#11)
#   currently not that pretty looking because of all the cannot stat errors (#9)
# -n if the filename already exists, won't move

# check and move
# chmov "${ex_tor[@]}" "$file" ${folders[0]}
chmov () {
	for ex in "$1"
	do
		if [[ $2 == *.$ex ]]; then
			mv -vn "$2" $3
		fi
	done
}

# loop through everything in folder
# check if it's a file
# using chmov above
# loop through extensions of each category
# and move files accordingly if they match any
for file in *
do
	if [ -f "$file" ]; then
		# torrent
		chmov "${ex_tor[@]}" "$file" ${folders[0]}
		# image
		chmov "${ex_img[@]}" "$file" ${folders[1]}
		# webm
		chmov "${ex_web[@]}" "$file" ${folders[2]}
		# exe
		chmov "${ex_exe[@]}" "$file" ${folders[3]}
		# compressed
		chmov "${ex_com[@]}" "$file" ${folders[4]}
		# video
		chmov "${ex_vid[@]}" "$file" ${folders[5]}
		# other
		chmov "${ex_oth[@]}" "$file" ${folders[6]}
	fi
done
