#!/bin/bash

# sets DNS configuration
# needs sudo ./resolvconf

cat >> /etc/resolv.conf << EOF
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
sudo resolvconf -u
# notify-send by itself didn't work for whatever reason
i3-msg exec notify-send "DNS set!"
